server:
  port: 8000

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: p^4s*SXxFm#*Wgdy
#    url: jdbc:mysql://inter-test.civqkugoooyc.ap-south-1.rds.amazonaws.com:3306/longmen_game?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Calcutta&allowMultiQueries=true

    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: GXENTF6Jz9TQo2Fx
    url: jdbc:mysql://baowang-test.cgudc1x5dlwm.ap-east-1.rds.amazonaws.com:3306/longmen_game?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Calcutta&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  #如果不配置此属性，resultType就得写全名resultType="com.itheima.domain.items"，
  #但是如果配置了此属性，就可以不用写全路径直接写resultType="items"即可
  type-aliases-package: com.example.appdemo.mybatis.entity

#各服务初始化方法执行开关
flag:
  ob-master: false
  ob-game: false
  ob-tag: true